/**
 * 测试 server/session-title-generator.js：标题清洗、生成与条件重命名。
 *
 * Keywords: session-title, test, openai-compatible
 *
 * Exports: 无导出，内含用例
 *
 * Inward: session-title-generator.js
 */
import test from 'node:test';
import assert from 'node:assert/strict';

import {
  generateSessionTitle,
  maybeAutoNameSession,
  sanitizeGeneratedTitle
} from './session-title-generator.js';

test('sanitizeGeneratedTitle keeps a compact task title and removes wrapper noise', () => {
  assert.equal(sanitizeGeneratedTitle('{"title":" Codex 线程智能命名。"}'), 'Codex 线程智能命名');
  assert.equal(sanitizeGeneratedTitle('标题：[$qingtian-sales-analysis] 李芳上周销售数据分析'), '李芳上周销售数据分析');
  assert.equal(sanitizeGeneratedTitle('https://example.com 这个链接帮我看看'), '这个链接帮我看看');
});

test('generateSessionTitle calls a small model and falls back to the local provisional title', async () => {
  const calls = [];
  const okFetch = async (url, options) => {
    calls.push({ url, body: JSON.parse(options.body), headers: options.headers });
    return {
      ok: true,
      text: async () => JSON.stringify({
        choices: [{ message: { content: '{"title":"Codex 桌面线程命名"}' } }]
      })
    };
  };

  const title = await generateSessionTitle({
    userMessage: '看一下我们现在codex桌面端它的一个线程是怎么起名的',
    assistantMessage: '现在不是模型智能命名，而是 preview 和 name 字段。',
    config: { baseUrl: 'http://127.0.0.1:8317/v1', apiKeys: ['test-key'] },
    fetchImpl: okFetch
  });

  assert.equal(title, 'Codex 桌面线程命名');
  assert.equal(calls.length, 1);
  assert.equal(calls[0].url, 'http://127.0.0.1:8317/v1/chat/completions');
  assert.equal(calls[0].body.model, 'gpt-5.4-mini');
  assert.equal(calls[0].headers.authorization, 'Bearer test-key');

  const fallback = await generateSessionTitle({
    userMessage: '帮我看一下移动端线程命名逻辑是什么',
    assistantMessage: 'irrelevant',
    config: { baseUrl: 'http://127.0.0.1:8317/v1', apiKeys: ['test-key'] },
    fetchImpl: async () => ({ ok: false, status: 500, text: async () => 'server error' }),
    logger: null
  });
  assert.equal(fallback, '移动端线程命名逻辑');
});

test('maybeAutoNameSession writes model title only for unlocked completed sessions', async () => {
  const renamed = [];
  const session = {
    id: 'thread-1',
    projectId: 'project-1',
    cwd: '/tmp/project',
    title: '看一下我们现在codex桌面端它的一个线程是怎么起名的',
    titleLocked: false,
    projectless: false
  };

  const result = await maybeAutoNameSession({
    session,
    userMessage: '看一下我们现在codex桌面端它的一个线程是怎么起名的',
    assistantMessage: '解释了 name、preview 和 thread/name/set。',
    renameSessionImpl: async (sessionId, projectId, title, options) => {
      renamed.push({ sessionId, projectId, title, options });
      return { ...session, title, titleLocked: false };
    },
    titleGenerator: async () => 'Codex 线程命名机制'
  });

  assert.equal(result.title, 'Codex 线程命名机制');
  assert.deepEqual(renamed, [{
    sessionId: 'thread-1',
    projectId: 'project-1',
    title: 'Codex 线程命名机制',
    options: { auto: true }
  }]);

  const locked = await maybeAutoNameSession({
    session: { ...session, titleLocked: true },
    userMessage: 'anything',
    assistantMessage: 'anything',
    renameSessionImpl: async () => {
      throw new Error('should not rename locked sessions');
    },
    titleGenerator: async () => 'Should Not Apply'
  });
  assert.equal(locked, null);

  const alreadyModelNamed = await maybeAutoNameSession({
    session: { ...session, titleAutoGenerated: 'model' },
    userMessage: '后续追问不应该改标题',
    assistantMessage: 'anything',
    renameSessionImpl: async () => {
      throw new Error('should not rename model-named sessions');
    },
    titleGenerator: async () => 'Should Not Apply'
  });
  assert.equal(alreadyModelNamed, null);
});
